// +build !ignore_autogenerated

// Code generated by openapi-gen. DO NOT EDIT.

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"sigs.k8s.io/addon-operators/coredns-operator/pkg/apis/addons/v1alpha1.CoreDNS":       schema_pkg_apis_addons_v1alpha1_CoreDNS(ref),
		"sigs.k8s.io/addon-operators/coredns-operator/pkg/apis/addons/v1alpha1.CoreDNSSpec":   schema_pkg_apis_addons_v1alpha1_CoreDNSSpec(ref),
		"sigs.k8s.io/addon-operators/coredns-operator/pkg/apis/addons/v1alpha1.CoreDNSStatus": schema_pkg_apis_addons_v1alpha1_CoreDNSStatus(ref),
	}
}

func schema_pkg_apis_addons_v1alpha1_CoreDNS(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "CoreDNS is the Schema for the coredns API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("sigs.k8s.io/addon-operators/coredns-operator/pkg/apis/addons/v1alpha1.CoreDNSSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("sigs.k8s.io/addon-operators/coredns-operator/pkg/apis/addons/v1alpha1.CoreDNSStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"sigs.k8s.io/addon-operators/coredns-operator/pkg/apis/addons/v1alpha1.CoreDNSSpec", "sigs.k8s.io/addon-operators/coredns-operator/pkg/apis/addons/v1alpha1.CoreDNSStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_addons_v1alpha1_CoreDNSSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "CoreDNSSpec defines the desired state of CoreDNS",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_addons_v1alpha1_CoreDNSStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "CoreDNSStatus defines the observed state of CoreDNS",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}
